/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CircleProgress: typeof import('./src/components/CircleProgress/index.vue')['default']
    IconBox: typeof import('./src/components/IconBox/index.vue')['default']
    Loading: typeof import('./src/components/Loading/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TitleBoard: typeof import('./src/components/TitleBoard/index.vue')['default']
    Toast: typeof import('./src/components/Toast/index.vue')['default']
    VanSwitch: typeof import('vant/es')['Switch']
  }
}
